management:
  server:
    port:
  endpoint:
    health:
      show-details: always
      show-components: always
spring:
  application:
    environment: local-docker
  main:
    log-startup-info: true
  data:
    redis:
      port: 6400
      host: localhost
  devtools:
    restart:
      enabled: false
digdir:
  event:
    logging:
      feature-enabled: false

eidas:
  eu-proxy:
    redirect-uri: http://eu-eidas-proxy:8082/SpecificProxyServiceResponse
  cache:
    secret: mySecretProxyserviceResponse
  oidc-integration:
    issuer: https://idporten.dev
    client-id: eidas-proxy-client-dev
    client-auth-method: client_secret_basic
    client-secret: 3aee797c-3fd4-46f2-8faf-ebff1a131055
    redirect-uri: http://localhost:8077/idpcallback
