management:
  server:
    port:
  endpoint:
    health:
      show-details: always
      show-components: always
spring:
  application:
    environment: local-docker
  main:
    log-startup-info: true

  data:
    redis:
      port: 6379
      host: redis

digdir:
  event:
    logging:
      feature-enabled: false

eidas:
  eu-proxy:
    redirect-uri: http://eu-eidas-proxy:8082/SpecificProxyServiceResponse
  cache:
    response-secret: mySecretProxyserviceResponse
    response-issuer-name: specificCommunicationDefinitionProxyserviceResponse
    request-secret: mySecretProxyserviceRequest
    request-issuer-name: specificCommunicationDefinitionProxyserviceRequest
    algorithm: SHA-256
    issuer-name: specificCommunicationDefinitionProxyserviceResponse
  oidc-integration:
    connect-timeout-millis: 5000
    read-timeout-millis: 5000
    jwks-cache-lifetime-minutes: 60
    jwks-cache-refresh-minutes: 5
    issuer: https://idporten.dev
    client-id: eidas-proxy-client-dev
    client-auth-method: client_secret_basic
    client-secret: 3aee797c-3fd4-46f2-8faf-ebff1a131055
    redirect-uri: http://localhost:8080/idpcallback
