management:
  endpoint:
    health:
      show-details: never
      show-components: always
spring:
  application:
    environment: prod
  data:
    redis:
      password: ${REDIS_PASSWORD}
      sentinel:
        master: mymaster
        password: ${REDIS_PASSWORD}
        nodes:
          - eidas-redis-sentinel-node-0.eidas-redis-sentinel-headless:26379
          - eidas-redis-sentinel-node-1.eidas-redis-sentinel-headless:26379
          - eidas-redis-sentinel-node-2.eidas-redis-sentinel-headless:26379
eidas:
  cache:
    response-secret: ${LIGHT_TOKEN_PROXYSERVICE_RESPONSE_SECRET}
    request-secret: ${LIGHT_TOKEN_PROXYSERVICE_REQUEST_SECRET}
  eu-proxy:
    redirect-uri: https://proxy.eidasnode.no/SpecificProxyServiceResponse
  oidc-integration:
    issuer: https://idporten.no
    client-id: eidas-proxy-client-prod
    client-auth-method: client_secret_basic
    client-secret: ${EIDAS_CLIENT_SECRET}
    redirect-uri: https://idporten-proxy.eidasnode.no/idpcallback
